= Klayr Core Binary Upgrade
Mona Bärenfänger <mona@lightcurve.io>
:description: The Klayr Core Binary Upgrade page describes how to upgrade Klayr Core to the latest version.
:toc:
:experimental:
:v_sdk: master

To upgrade Klayr Core from Binary please follow the instructions below.
Please choose the instructions specific to the network (Mainnet or Testnet) your node is connected to.

== Upgrade with Klayr Commander

IMPORTANT: The `core:upgrade` command is only supported for Klayr Core versions > `2.0.0` and will only work, if Klayr Core has been installed with Klayr Commander before.

First, go into the directory, where your Klayr Core installation is located.

Then, run the following command to upgrade Klayr Core:

[source,bash]
----
klayr core:upgrade <location>
----

Where `<location>` should be the root folder of your Klayr Core installation.

See for all available options the Klayr Commander xref:{v_sdk}@klayr-sdk::klayr-commander/user-guide/klayr-core.adoc[Command reference for Klayr Core] as well as the xref:{v_sdk}@klayr-sdk::klayr-commander/user-guide/commands.adoc[general Command reference] .

== Upgrade with bash script

=== Mainnet

[source,bash]
----
cd ~
rm -f installKlayr.sh
wget https://downloads.klayr.io/klayr/main/installKlayr.sh
bash installKlayr.sh upgrade -r main
----

=== Testnet

[source,bash]
----
cd ~
rm -f installKlayr.sh
wget https://downloads.klayr.io/klayr/test/installKlayr.sh
bash installKlayr.sh upgrade -r test
----

After running the above script manually or through `klayr_bridge.sh`, you will be prompted to pick from a few options.
Please read these thoroughly and follow the steps.

[NOTE]
====
You have to enable forging manually after the upgrade.
Please follow this guide to xref:configuration.adoc#_forging[enable forging on your delegate node] for further details.
====

== Manual Upgrade Klayr Core

Switch to your Klayr folder and stop Klayr processes:

[tabs]
====
Mainnet::
+
--
[source,bash]
----
cd ~
cd klayr-main
bash klayr.sh stop
----
--
Testnet::
+
--
[source,bash]
----
cd ~
cd klayr-test
bash klayr.sh stop
----
--
====

Backup your SSL folder (if needed):

[source,bash]
----
mkdir ~/backup
cp -f ./ssl/* ~/backup/
cp -f ./config.json ~/backup/
----

Remove your old Klayr folder and install script:

[tabs]
====
Mainnet::
+
--
[source,bash]
----
cd ~
rm -rf ~/klayr-main
rm -rf installKlayr.sh
----
--
Testnet::
+
--
[source,bash]
----
cd ~
rm -rf ~/klayr-test
rm -rf installKlayr.sh
----
--
====

Get the latest install script:

[tabs]
====
Mainnet::
+
--
[source,bash]
----
wget https://downloads.klayr.io/klayr/main/installKlayr.sh
----
--
Testnet::
+
--
[source,bash]
----
wget https://downloads.klayr.io/klayr/test/installKlayr.sh
----
--
====

Install the latest version of Klayr:

[tabs]
====
Mainnet::
+
--
[source,bash]
----
bash installKlayr.sh install -r main
----
--
Testnet::
+
--
[source,bash]
----
bash installKlayr.sh install -r test
----
--
====

TIP: You will be prompted for your installation directory, pressing kbd:[Enter] will choose the default.
