= Klayr Core Upgrade with Klayr Commander
Mona Bärenfänger <mona@lightcurve.io>
:description: The Klayr Core Commander Upgrade page describes how to upgrade Klayr Core to the latest version via Klayr Commander.
:toc:
:v_core: 2.1.3

NOTE: The `core:upgrade` command is only supported for Klayr Core versions greater than 2.0.0.

== Upgrade

[tabs]
=====
Mainnet::
+
--
To upgrade Klayr Core, run the following command in your terminal:

[source,bash]
----
klayr core:upgrade klayr-mainnet <1>
----
<1> Exchange `INSTANCE` with the name of your Klayr Core instance, which you chose during the xref:setup/commander.adoc[Installation of Klayr Core].
--
Testnet::
+
--
To upgrade Klayr Core, run the following command in your terminal:

[source,bash]
----
klayr core:upgrade klayr-testnet <1>
----
<1> Exchange `INSTANCE` with the name of your Klayr Core instance, which you chose during the xref:setup/commander.adoc[Installation of Klayr Core].
--
=====

[TIP]
====
If you forgot the name of the Klayr instance, have a look into the `instances` directory:

[source,bash]
----
ls ~/.klayr/instances/ <1>
----
<1> Lists all available Klayr Core instances
====

== Available options

Add one or multiple of the options below to the `core:upgrade` command. Multiple options are seperated by spaces.

|===
| Full Name | Short Name | Examples | Description

| `--release-url` | `-r`
| `--release-url=https://my-custom.url/testnet/2.1.0-rc.0/klayr-2.1.0-rc.0-Linux-x86_64.tar.gz`
| Define a custom URL for downloading the new Klayr Core binary script.
You also need to have the checksum for the TAR file with the format 2.0.0-Linux-x86_64.tar.gz.SHA256 for the Commander to check the integrity of the binary.
You can refer to our https://downloads.klayr.io/klayr/mainnet/{v_core}/[binary release] for the file naming convention.

| `--klayr-version`
| N/A
a|
* `--klayr-version=2.0.0`
* `--klayr-version=2.1.3`
| Define the concrete version, Klayr Core should be upgraded to.
|===
