= Client
Mona Bärenfänger <mona@lightcurve.io>
:description: Technical references regarding the clients packages of Klayr Elements. This consists of references to all included sub-packages and general usage instructions.
:toc:
:url_elements_api: reference/klayr-elements/api-client.adoc
:url_elements_constants: reference/klayr-elements/constants.adoc
:url_elements_cryptography: reference/klayr-elements/cryptography.adoc
:url_elements_passphrase: reference/klayr-elements/passphrase.adoc
:url_elements_transactions: reference/klayr-elements/transactions.adoc

This provides a default set of packages for use by clients of the Klayr network.

[NOTE]
====
The `Client` package is a collection of the following packages:

xref:{url_elements_api}[api-client], xref:{url_elements_constants}[constants],
xref:{url_elements_cryptography}[cryptography], xref:{url_elements_passphrase}[passphrase],
xref:{url_elements_transactions}[transactions]
====

Klayr Elements will include numerous different packages in the future which can be plugged in to applications as desired.

For enhanced usability Klayr Elements provides special wrapper packages such as `klayr-client`, whose group packages are often used in the same context.

== Installation

To add Klayr client as a dependency of your project execute the following command:

[source,bash]
----
$ npm install @klayrhq/klayr-client
----

== Upgrade

To perform an upgrade, execute the following command:

[source,bash]
----
npm update @klayrhq/klayr-client
----

== Usage

Import using ES6 modules syntax:

[source,js]
----
import klayr from '@klayrhq/klayr-client';
----

Or using Node.js modules:

[source,js]
----
const klayr = require('@klayrhq/klayr-client');
----

Or import specific namespaced functionality:

[source,js]
----
import { APIClient, transactions } from '@klayrhq/klayr-client';
// or
const { APIClient, transactions } = require('@klayrhq/klayr-client');
----
