= Binary setup
Mona Bärenfänger <mona@lightcurve.io>
:description: How to install and setup a Klayr Core (binary distribution).
:toc:
// External URLs
:url_set_path: https://opensource.com/article/17/6/set-path-linux
// Project URLs
:url_run_logging: ROOT::run-blockchain/logging.adoc

The binary installation offers an easy and automated approach to set up Klayr Core.

== Pre-Installation

=== Supported Platforms
* Ubuntu 18.04 (LTS) x86_64
* Ubuntu 20.04 (LTS) x86_64
* MacOS x86_64

include::partial$create-a-new-user.adoc[]

[[install]]
== Installation

This section details how to install Klayr Core using pre-built application packages.
Once completed, you will have a functioning node on the Klayr Network.

=== Download and execute the installation script

Download Klayr Core:

[tabs]
====
Mainnet::
+
--
*Linux:*

[source,bash]
----
curl -o klayr-core.tar.gz https://downloads.klayr.xyz/klayr/mainnet/3.1.1/klayr-core-v3.1.1-linux-x64.tar.gz
----

*MacOS:*

[source,bash]
----
curl -o klayr-core.tar.gz https://downloads.klayr.xyz/klayr/mainnet/3.1.1/klayr-core-v3.1.1-darwin-x64.tar.gz
----
--
Testnet::
+
--
*Linux:*

[source,bash]
----
curl -o klayr-core.tar.gz https://downloads.klayr.xyz/klayr/testnet/3.1.1/klayr-core-v3.1.1-linux-x64.tar.gz
----

*MacOS:*

[source,bash]
----
curl -o klayr-core.tar.gz https://downloads.klayr.xyz/klayr/testnet/3.1.1/klayr-core-v3.1.1-darwin-x64.tar.gz
----
--
====

Unpack it, and add it to the system path, in order to use it in the terminal:

[source,bash]
----
tar -xf ./klayr-core.tar.gz
cd klayr-core
./bin/klayr-core
----

[TIP]

====

You can make the `klayr-core` command available in the PATH, e.g. by executing the following:

[source,bash]
----
export PATH="$PATH:$HOME/klayr-core/bin"
----

See {url_set_path}[^] for more information.

To make `klayr-core` permanently available in the CLI, add the above snippet to `~/.bashrc`.

To reload `.bashrc`, run the following command:

[source,bash]
----
source ~/.bashrc
----
====

=== Verify successful installation

To verify that your Klayr node is up and running, execute the following command:

[tabs]
====
Mainnet::
+
--
[source,bash]
----
klayr-core start --network mainnet
----

[NOTE]
=====
The default log levels for Mainnet are:

[source,json]
----
"logger": {
    "fileLogLevel": "error",
    "consoleLogLevel": "none"
},
----

So if you start the node, it won't show any logs in the console.
This is the recommended setting for reducing the number of logs for a running node.
However, to verify that the node started correctly, update the log levels in the config to `info` or lower.

Alternatively, start the node with the following flag:

[source,bash]
----
klayr-core start --network mainnet --console-log=info
----

See the xref:{url_run_logging}[] guide for more information about logging.
=====
--
Testnet::
+
--
[source,bash]
----
klayr-core start --network testnet
----
--
====

include::partial$core-post-installation.adoc[]
