= Klayr Core Binary Setup
Mona Bärenfänger <mona@lightcurve.io>
:description: The Klayr Core Binary Setup describes all necessary steps and requirements to install the Klayr SDK.
:toc:
:v_sdk: master

This document details how to setup Klayr Core Binary distribution on a system.

== Pre-Install

To complete the installation some prerequisites need to be fulfilled.
If you have already performed these, please proceed to the <<_installation, Installation>> chapter.

=== Determine if your platform can run Klayr Core

==== Supported Platforms

* Ubuntu 18.04 (LTS) x86_64
* Ubuntu 16.04 (LTS) x86_64


include::partial$core-ports.adoc[]

=== Install dependencies

[source,bash]
----
sudo apt-get update
sudo apt-get install curl wget tar unzip zip ntp
----

include::partial$create-a-new-user.adoc[]

== Installation

This section details how to install Klayr Core using pre-built binary packages.
Once completed, you will have a functioning node on the Klayr Network.
If you are looking to upgrade your current Klayr Core installation, please see the xref:upgrade/binary.adoc[Upgrade Binary] section.

=== Login to the Klayr user

The user was created in the <<pre-install,Binary - Prerequisites Section>>.
If you are already logged in to this user, please skip this step.

[source,bash]
----
sudo -u klayr -i
----

=== Execute the installation script

This will configure the environment, download and install Klayr Core.
Before proceeding, determine whether you wish to connect your node to the Testnet (Test Network) or the Mainnet (Main Network).

[tabs]
====
Mainnet::
+
--
Download Klayr Core:

[source,bash]
----
wget https://downloads.klayr.io/klayr/main/installKlayr.sh
----

To connect your node to the Mainnet, run:

[source,bash]
----
bash installKlayr.sh install -r main
----
--
Testnet::
+
--
Download Klayr Core:

[source,bash]
----
wget https://downloads.klayr.io/klayr/test/installKlayr.sh
----

To connect your node to the Testnet, run:

[source,bash]
----
bash installKlayr.sh install -r test
----
--
====

You will be prompted for your installation directory, pressing enter will choose the default.

Next, you will be prompted, if you wish to synchronize from the Genesis block.
If you answer `no', which is the default option, the node will download a recent snapshot of the database.
This will be much faster than synching from the genesis block.

The installation may take a few minutes.
Check the output of the script to verify that the installation was successful.

If you recognize an error, try to resolve it by analyzing the error output, otherwise, you can have a look at our xref:troubleshooting.adoc[Troubleshooting Section].

=== Verify successful installation

When the installation script has finished, navigate inside of the newly created folder `klayr-main`(for Mainnet) or `klayr-test`(for Testnet).
You can verify that your Klayr node is up and running, by running the following command:

[source,bash]
----
bash klayr.sh status
----

For further information and how to administer your Klayr node, please have a look at our xref:administration/binary.adoc[Administration Section].

If you are not running Klayr locally, you will need to follow the xref:configuration.adoc#_api_access_control[Configuration - API] document to enable access.

With all of the above steps complete you are ready to move on to the configuration documentation if you wish to enable forging or SSL, please see xref:configuration.adoc[General Configuration].

== Post-installation (optional)

* Recommended: Set up a xref:configuration.adoc#_logrotation[log rotation]
