= Klayr Core Setup with Klayr Commander
Mona Bärenfänger <mona@lightcurve.io>
:description: The Klayr Core Commander Setup describes all necessary steps and requirements to install the Klayr SDK via Klayr Commander.
:toc:
:v_sdk: master
:v_core: 2.1.3

Setup and manage your Klayr node conveniently with Klayr Commander.

[NOTE]
====
This setup option is supported from Klayr Core v2.0.0 upwards.
If you have Klayr Core v1.6 or lower installed, you won't be able to upgrade your node with Klayr Commander.
In this case, use the bash script or remove your old version and make a fresh install with Klayr Commander.
====

== Supported Platforms

* Ubuntu 18.04 (LTS) x86_64
* Ubuntu 16.04 (LTS) x86_64
* MacOS 10.12 (Sierra)
* MacOS 10.13 (High Sierra)

== Pre-Install

To complete the installation some prerequisites need to be fulfilled.
If you have already performed these, please proceed to the <<_installation, Installation>> chapter.

=== Install Klayr Commander

Head to the Klayr Commander docs and follow the xref:{v_sdk}@klayr-sdk::klayr-commander/index.adoc#_setup[installation instructions].

Once Klayr Commander is set up on your system, you can use the commands below to set up/manage your Klayr Core node.

== Installation

[IMPORTANT]
====
Don't run this command with a user with `sudo` rights. +
If you do so, the installation will be aborted, as it is not needed and recommended to install Klayr Core for a user with `sudo` rights.
====

[TIP]
====
You can freely choose the name of your Klayr Core instance.

Just be aware that you need to refer to your custom name instead of `klayr-mainnet` or `klayr-testnet` when running the commands.
====

[tabs]
====
Mainnet::
+
--
[source,bash]
----
klayr core:install klayr-mainnet
----

This will install Klayr Core latest version into a directory `~/.klayr/instances/klayr-mainnet`.

To verify your node is running correctly, run e.g.

[source,bash]
----
klayr core:status klayr-mainnet
----
--
Testnet::
+
--
[source,bash]
----
klayr core:install --network=testnet klayr-testnet
----

This will install Klayr Core latest version into a directory `~/.klayr/instances/klayr-testnet`.

To verify your node is running correctly, run e.g.

[source,bash]
----
klayr core:status klayr-testnet
----
--
====

TIP: See for all available options the Klayr Commander xref:{v_sdk}@klayr-sdk::klayr-commander/user-guide/klayr-core.adoc[Command reference for Klayr Core] as well as the xref:{v_sdk}@klayr-sdk::klayr-commander/user-guide/commands.adoc[general Command reference].

=== Available options

Add one or multiple of the options below to the `core:install` command. Multiple options are seperated by spaces.

|===
| Full Name | Short Name | Examples | Description

| `--network` | `-n`
a|
* `--network=testnet`
* `--network=betanet`
* `-n=alphanet`
* `--network=devnet`
| The network, you want to Klayr Core to connect to. If you don't specify this option, it will connect to the default network (Mainnet).

| `--release-url` | `-r`
| `--release-url=https://my-custom.url/testnet/2.1.0-rc.0/klayr-2.1.0-rc.0-Linux-x86_64.tar.gz`
| Define a custom URL for downloading the new Klayr Core binary script.
You also need to have the checksum for the TAR file with the format 2.0.0-Linux-x86_64.tar.gz.SHA256 for the Commander to check the integrity of the binary.
You can refer to our https://downloads.klayr.io/klayr/mainnet/{v_core}/[binary release] for the file naming convention.

| `--klayr-version` | N/A
a|
* `--klayr-version=2.0.0`
* `--klayr-version=2.1.3`
| Define the concrete version, Klayr Core should be upgraded to.
If you don't specify the version, it will install the latest stable version of Klayr Core.

| `--snapshot-url` | `-s`
| `--snapshot-url=http://snapshots.klayr.io.s3-eu-west-1.amazonaws.com/klayr/testnet/klayr_test_backup-9299232.gz`
| Define a custom URL for downloading the xref:index.adoc#_snapshots[snapshot], that should be used during the setup of Klayr Core.

| `--no-snapshot` | N/A
| N/A | Set this option, if you do not want to use any snapshot during the setup of Klayr Core.
In this case, your node will synchronize the whole blockchain, starting from genesis block.
If you choose this option, the setup process will take a significantly longer time.

| `--no-start` | N/A
| N/A | Set this option, if you don't want to start Klayr Core automatically after the installation.
|===


== Post-Install

After installation, check which ports Klayr Core is listening by checking the status:

[tabs]
====
Mainnet::
+
--
[source,bash]
----
klayr core:status klayr-mainnet
----
--
Testnet::
+
--
[source,bash]
----
klayr core:status klayr-testnet
----
--
====

Check you network settings to verify the corresponding ports are open.

It’s also recommended to set up a xref:configuration.adoc#_logrotation[log rotation].

If you are not running Klayr locally, you will need to follow the xref:configuration.adoc#_api_access_control[Configuration - API] document to enable access.

With all of the above steps complete you are ready to move on to the configuration documentation if you wish to enable forging or SSL, please see xref:configuration.adoc[General Configuration].
