= Docker setup
Mona Bärenfänger <mona@lightcurve.io>
:description: How to install and setup up a Klayr Core node with Docker.
:toc:
// Settings
// External URLs
:url_core_releases: https://github.com/KlayrHQ/klayr-core/releases
:url_podman: https://github.com/containers/podman/
:url_docker_install: https://docs.docker.com/engine/installation/#desktop
:url_docker_install_linux: https://docs.docker.com/engine/installation/#server
:url_docker_install_mac: https://docs.docker.com/docker-for-mac/install/
:url_docker_install_windows: https://docs.docker.com/docker-for-windows/install/
:url_docker_linux_post_install: https://docs.docker.com/install/linux/linux-postinstall
:url_xcode: https://developer.apple.com/xcode/features/
// Project URLs
:url_config: management/configuration.adoc
:url_upgrade_source: update/source.adoc
:url_run_logging: ROOT::run-blockchain/logging.adoc

This document describes how to run Klayr Core as a Docker image-based container.
Klayr Core version 3 does not have any external dependencies, and hence does not require using `docker-compose`.

== Pre-installation

=== Create a new user `klayr`

[source,bash]
----
adduser klayr
----

Add the `klayr` user to the `sudo` user group:

[source,bash]
----
sudo usermod -aG sudo klayr
----

=== Install Docker
To run Klayr Core in Docker, firstly it is necessary to install the Docker engine.
Determine if your platform can run Docker as described below.

Please refer to {url_docker_install}[https://docs.docker.com/engine/installation]

[tabs]
====
Ubuntu::
+
--
Please refer to {url_docker_install_linux}[Docker installation for ubuntu]

IMPORTANT: Configure Docker, in order that it can be run without `sudo` rights: {url_docker_linux_post_install}[linux post install]

Install `make` using your package manager.
For example, use `apt-get` if running Ubuntu as shown below:

[source,bash]
----
sudo apt-get install curl make
----
--
MacOS::
+
--
Please refer to {url_docker_install_mac}[Docker installation for Mac^].
Install `make` using {url_xcode}[XCode].
--

Windows::
+
--
Please refer to {url_docker_install_windows}[Docker installation for Windows^]
--
====



== Klayr Core download

[source,bash]
----
git clone https://github.com/KlayrHQ/klayr-core.git #<1>
cd klayr-core/docker                  #<2>
git checkout v3.1.1 -b v3.1.1 #<3>
----

<1> Clone the repository.
<2> Navigate into the klayr-core root folder.
<3> Check out the latest release tag.

NOTE: Please check for the latest release in the {url_core_releases}[Klayr Core releases^] list.

== Run

.Podman
[NOTE]
====
{url_podman}[podman] can be used.
Simply replace occurrences of `docker` with `podman` or `alias docker=podman`.
====

Create a "klayr-core" container:

[tabs]
====
Mainnet::
+
--

[source,bash]
----
docker run --volume klayr-data:/home/klayr/.klayr \
           --publish 5001:5001 \
           --name klayr-core \
           klayr/core:3.1.1 \
             start --network=mainnet
----

[NOTE]
=====
The default log levels for Mainnet are:

[source,json]
----
"logger": {
    "fileLogLevel": "error",
    "consoleLogLevel": "none"
},
----

So if you start the node, it won't show any logs in the console.
This is the recommended setting for reducing the number of logs for a running node.
However, to verify that the node started correctly, update the log levels in the config to `info` or lower.

Alternatively, start the node with the following flag:

[source,bash]
----
start --network mainnet --console-log=info
----

See the xref:{url_run_logging}[] guide for more information about logging.
=====
--
Testnet::
+
--

[source,bash]
----
docker run --volume klayr-data:/home/klayr/.klayr \
           --publish 5001:5001 \
           --name klayr-core \
           klayr/core:3.1.1 \
             start --network=testnet
----
--
====

== Configuration

Further parameters can be passed after `--network`, for example, as shown below:

[source,bash]
----
docker run --volume klayr-data:/home/klayr/.klayr \
           --publish 5001:5001 \
           --publish 127.0.0.1:5000:5000 \
           --name klayr-core \
           klayr/core:3.1.1 \
             start --network=testnet --enable-http-api-plugin
----

Environment variables can be set with `--env`:

[source,bash]
----
docker run --volume klayr-data:/home/klayr/.klayr \
           --publish 5001:5001 \
           --env KLAYR_CONSOLE_LOG_LEVEL=debug \
           --name klayr-core \
           klayr/core:3.1.1 \
             start --network=testnet
----

See the xref:{url_config}[] guide for a reference of more configuration options.

An example with all possible flags set is shown below:

[source,bash]
----
docker run -d --volume /data:/home/klayr/.klayr \
    --publish 7000:7000 --publish 8080:8080 --publish 7008:7008\
    --name klayr-core klayr/core:3.1.1 start --network=testnet --port 7000\
    --api-ws --enable-http-api-plugin --http-api-plugin-port 7008\
    --http-api-plugin-host host.docker.internal --http-api-plugin-whitelist 0.0.0.0/0 \
    --api-ws --api-ws-port 8080 --api-ws-host 0.0.0.0
----

== Import blockchain snapshot

[source,bash]
----
docker run --volume klayr-data:/home/klayr/.klayr -it --rm klayr/core:3.1.1 blockchain:download --network=betanet --output=/home/klayr/.klayr/tmp/
docker run --volume klayr-data:/home/klayr/.klayr -it --rm klayr/core:3.1.1 blockchain:import /home/klayr/.klayr/tmp/blockchain.db.tar.gz
docker run --volume klayr-data:/home/klayr/.klayr -it --rm --entrypoint rm klayr/core:3.1.1 -f /home/klayr/.klayr/tmp/blockchain.db.tar.gz
docker start klayr-core
docker logs -f klayr-core
----
