= Installation with Docker
Mona Bärenfänger <mona@lightcurve.io>
:description: Describes all necessary steps and requirements to install Klayr Service with Docker.
:toc:
:experimental:
:page-next: /klayr-service/configuration/docker.html
:page-next-title: Configuration with Docker
:sectnums:

:url_github_service: https://github.com/KlayrHQ/klayr-service
:url_docker_hub: https://hub.docker.com/
:url_docker_install_linux: https://docs.docker.com/engine/install
:url_docker_install_linux_compose: https://docs.docker.com/compose/install/
:url_docker_install_mac: https://docs.docker.com/docker-for-mac/install/
:url_docker_install_windows: https://docs.docker.com/docker-for-windows/install/
:url_docker_linux_post_install: https://docs.docker.com/install/linux/linux-postinstall/
:url_xcode: https://developer.apple.com/xcode/features/

:url_index_usage: index.adoc#usage
:url_setup: setup/index.adoc
:url_core_setup_npm: v3@klayr-core::setup/npm.adoc
:url_config: configuration/docker.adoc
:url_management: management/docker.adoc
:url_references_config: reference/configuration.adoc

:url_core_setup_binary: v3@klayr-core::setup/binary.adoc

How to set up Klayr Service and connect it to a local Klayr Core node.

== Setting up Klayr Core

Klayr Service is installed in addition to a Klayr blockchain application such as Klayr Core, in order to provide enriched network data for third-party services.

The first step is therefore to install Klayr Core.

It is recommended to use NPM to conveniently install Klayr Core through the command line:

[source,bash]
----
npm install --global --production klayr-core
----

Check out the xref:{url_core_setup_npm}[Klayr Core NPM setup] guide for more information on how to install Klayr Core on your machine.

== Configuring Klayr Core

Use the Klayr Core CLI to start Klayr Core with the desired configurations.

* The `--network` flag determines the blockchain network Klayr Core connects to.
* `--api-ws` enables the WebSocket API of the node, if not already enabled within the config.json file.
* `--api-ws-host=0.0.0.0` allows remote servers to connect to the Klayr Core WS API.
If this option is not set, it defaults to `127.0.0.1`.
* `--api-ws-port=8080` the port for the WebSocket API.

[source,bash]
----
klayr-core start --network mainnet --api-ws --api-ws-host=0.0.0.0 --api-ws-port=8080
----

To connect to a different network, replace `mainnet` with either `testnet` or `devnet`.

== Setting up Klayr Service

[IMPORTANT]
====
It is strongly recommended to synchronize your Klayr Core node with the network **before** starting the Klayr Service.
====

=== Prerequisites

The following dependencies are required to install and run Klayr Service with Docker.

==== Development tools

[tabs]
====
Ubuntu / Debian::
+
--
Install the `build-essential` package alongside with several development tools.

For example, use `apt` if running Ubuntu as shown in the following command below:

[source,bash]
----
apt install build-essential git
----
--
MacOS::
+
--

*Brew*

Install https://brew.sh/[Brew] by following https://brew.sh/[the most recent instruction].

If you already have Brew installed, ensure it is working and is the latest version.

[source,bash]
----
brew update
brew doctor
----

*Xcode*

Install https://developer.apple.com/xcode/[Xcode] essentials coming from Apple.

[source,bash]
----
xcode-select --install
----
--
====

==== Docker & Docker compose

[tabs]
====
Ubuntu / Debian::
+
--
. Please refer to {url_docker_install_linux}[docker installation for ubuntu^].
. To install Docker Compose, please refer to {url_docker_install_linux_compose}[install docker compose^].
. To configure Docker so it can be run without `sudo` rights, follow: {url_docker_linux_post_install}[linux post install^].
--
MacOS::
+
--
. Please refer to {url_docker_install_mac}[Docker installation for Mac^]. Please note that Docker for Mac already includes Docker Compose.
. Install `make` using {url_xcode}[XCode^].
--
====

==== Open necessary ports

Ensure the port which allows external services communication with the Klayr Service APIs is open.

- 9901: Default API port (HTTP & WebSocket)

.Example: Opening the port 9001 with ufw on Ubuntu
[source,bash]
----
sudo ufw allow 9901
----

=== Installation of Klayr Service

Clone the {url_github_service}[klayr-service^] GitHub repository and then navigate into the project folder.

.In the directory where you want to store Klayr Service
[source,bash]
----
git clone https://github.com/KlayrHQ/klayr-service.git
cd klayr-service
git checkout v0.6.6
----

== Build Klayr Service

Build Klayr Service from local files:

./klayr-service/
[source,bash]
----
make build
----

Klayr Service is now ready to use on your machine.

TIP: If you skipped the step to configure Docker to run without `sudo` rights, you need to prepend `sudo`: `sudo make build`

== Connecting Klayr Service to Klayr Core

Before running the application copy the default docker-compose environment file:

[source,bash]
----
cp docker/example.env .env
----

In the next step, open `.env` and set the required environment variables.

[source,bash]
----
vim .env
----


..env
[source,bash]
----
# Klayr ecosystem configuration
KLAYR_CORE_WS=ws://host.docker.internal:8080 #<1>
----

<1> The example assumes that the Klayr Core node is running on the host machine, and not inside of a Docker container.
When running Klayr Core inside of a Docker container, the variable needs to refer to the container: `KLAYR_CORE_WS="ws://<your_docker_container>:8080"`.

TIP: For a complete list of supported environment variables check the xref:{url_references_config}[].

== Starting Klayr Service

Run the following command to start Klayr Service:

[source,bash]
----
make up
----

== Stopping Klayr Service
You can stop Klayr Service again with the following command:

[source,bash]
----
make down
----

More commands about how to manage Klayr Service are described on the xref:{url_management}[Docker commands] page.

TIP: Check the xref:{url_index_usage}[Usage] section for examples of how to use and interact with Klayr Service.
