= Update Klayr Core (Binary)
Mona Bärenfänger <mona@lightcurve.io>
:description: How to update Klayr Core to the latest version (Binary).
:toc:
:sectnums:
:experimental:
// Project URLs
:url_enable_forging: management/forging.adoc

How to update the Klayr Core binary distribution to a new version.

== Download the new Klayr Core version

Download the new Klayr Core version inside of your user home directory.

[tabs]
====
Mainnet::
+
--
*Linux:*

[source,bash]
----
wget https://downloads.klayr.io/klayr/main/3.1.1/klayr-core-v3.1.1-linux-x64.tar.gz
wget https://downloads.klayr.io/klayr/main/3.1.1/klayr-core-v3.1.1-linux-x64.tar.gz.SHA256
----

*MacOS:*

[source,bash]
----
wget https://downloads.klayr.io/klayr/main/3.1.1/klayr-core-v3.1.1-darwin-x64.tar.gz
wget https://downloads.klayr.io/klayr/main/3.1.1/klayr-core-v3.1.1-darwin-x64.tar.gz.SHA256
----
--
Testnet::
+
--
*Linux:*

[source,bash]
----
wget https://downloads.klayr.io/klayr/test/3.1.1/klayr-core-v3.1.1-linux-x64.tar.gz
wget https://downloads.klayr.io/klayr/test/3.1.1/klayr-core-v3.1.1-linux-x64.tar.gz.SHA256
----

*MacOS:*

[source,bash]
----
wget https://downloads.klayr.io/klayr/test/3.1.1/klayr-core-v3.1.1-darwin-x64.tar.gz
wget https://downloads.klayr.io/klayr/test/3.1.1/klayr-core-v3.1.1-darwin-x64.tar.gz.SHA256
----
--
====

== Verify Checksum

[tabs]
====
Linux::
+
--
[source,bash]
----
sha256sum -c klayr-core-v3.1.1-linux-x64.tar.gz.SHA256
# klayr-core-v3.1.0-linux-x64.tar.gz: OK
----
--
MacOS::
+
--
[source,bash]
----
sha256sum -c klayr-core-v3.1.1-darwin-x64.tar.gz.SHA256
----
--
====

== Stop Klayr Core

[source,bash]
----
pm2 delete klayr-core
----

== Backup Klayr Core
=== Backup your custom configs

In case you created custom configurations inside the `klayr-core/` folder, make sure to copy or move them out of the `klayr-core/` folder before removing them in the next step.

* `custom-config.json`: backup the custom configuration for Klayr Core.
* `pm2.conf.json`: backup the pm2 config file.

=== Backup the application data
[source,bash]
----
tar czf ~/backup_klayr.tar.gz ~/.klayr/
----

== Remove the old version

[source,bash]
----
rm -rf ~/klayr-core/
----

== Extract the new version

[tabs]
====
Linux::
+
--
[source,bash]
----
tar xzf ~/klayr-core-v3.1.1-linux-x64.tar.gz -C ~/
----
--
MacOS::
+
--
[source,bash]
----
tar xzf ~/klayr-core-v3.1.1-darwin-x64.tar.gz -C ~/
----
--
====

== Start Klayr Core

Note: If you have configured your `pm2.config.json`, please use that configuration.

[source,bash]
----
pm2 start pm2.conf.json
----

== Sanity Check

Verify the correct version.

[source,bash]
----
klayr-core --version
#klayr-core/3.1.1 linux-x64 node-v18
----

Check if the new `transferFixHeight, serializationFixHeight` is correctly set:

* `transferFixHeight, serializationFixHeight` value for the Mainnet is `17557156`.
* `transferFixHeight, serializationFixHeight` value for the Testnet is `15466999`.

.Example: Checking transferFixHeight, serializationFixHeight for Testnet
[source,bash]
----
klayr-core node:info --pretty | grep "serializationFixHeight\|transferFixHeight"
"transferFixHeight, serializationFixHeight": 15466999
----

.For delegates
NOTE: *For delegates:* Don't forget that xref:{url_enable_forging}[] again is required after the update.

