= Docker image
Mona Bärenfänger <mona@lightcurve.io>
:description: How to upgrade Klayr Core with Docker.
:toc:

:url_core_repository: https://github.com/KlayrHQ/klayr-core
:url_current_version: https://github.com/KlayrHQ/klayr-core/tree/development/docker
:url_version_tag: https://github.com/KlayrHQ/klayr-core/tags

[[minor-version]]
== Upgrade minor versions

To update a Klayr installation using Docker Compose it is only required to export the new version number in `ENV_KLAYR_VERSION`.

Example: Update from Klayr Core by executing the following commands:

[source,bash]
----
export ENV_KLAYR_VERSION=3.1.1
docker-compose up -d
----

== Update major versions

For major version updates there may be additional changes in `docker-compose.yml`.

In this case Klayr Core provides an updated version of `docker-compose.yml` in the {url_core_repository}[Klayr Core repository^] on Github, inside the `docker` folder: {url_current_version}[current version^].

(Where the `<CURRENT_VERSION>` is the {url_version_tag}[version tag^] of the update version you wish to use.)

Use this file as a new template for your `docker-compose.yml`.

The remainder of the upgrade process is analog to the <<minor-version,minor version upgrade>>.
