= Klayr Core commands
Mona Bärenfänger <mona@lightcurve.io>
:description: Technical reference regarding each available command used to manage Klayr Core with Klayr Commander. For all commands and all available options a usage example and an example response is given.
:toc:
:v_core: 3.0.0
:v_sdk: v3.0.2
:url_core_setup_binary: {v_core}@klayr-core::setup/binary.adoc
:url_github_commander_core_install: https://github.com/KlayrHQ/klayr-sdk/blob/{v_sdk}/commander/src/commands/core/install.ts
:url_github_commander_core_logs: https://github.com/KlayrHQ/klayr-sdk/blob/{v_sdk}/commander/src/commands/core/logs.ts
:url_github_commander_core_restart: https://github.com/KlayrHQ/klayr-sdk/blob/{v_sdk}/commander/src/commands/core/restart.ts
:url_github_commander_core_start: https://github.com/KlayrHQ/klayr-sdk/blob/{v_sdk}/commander/src/commands/core/start/index.ts
:url_github_commander_core_cache: https://github.com/KlayrHQ/klayr-sdk/blob/{v_sdk}/commander/src/commands/core/start/cache.ts
:url_github_commander_core_database: https://github.com/KlayrHQ/klayr-sdk/blob/{v_sdk}/commander/src/commands/core/start/database.ts
:url_github_commander_core_status: https://github.com/KlayrHQ/klayr-sdk/blob/{v_sdk}/commander/src/commands/core/status.ts
:url_github_commander_core_stop: https://github.com/KlayrHQ/klayr-sdk/blob/{v_sdk}/commander/src/commands/core/stop/index.ts
:url_github_commander_core_stop_cache: https://github.com/KlayrHQ/klayr-sdk/blob/{v_sdk}/commander/src/commands/core/stop/cache.ts
:url_github_commander_core_stop_database: https://github.com/KlayrHQ/klayr-sdk/blob/{v_sdk}/commander/src/commands/core/stop/database.ts
:url_github_commander_core_uninstall: https://github.com/KlayrHQ/klayr-sdk/blob/{v_sdk}/commander/src/commands/core/uninstall.ts
:url_github_commander_core_upgrade: https://github.com/KlayrHQ/klayr-sdk/blob/{v_sdk}/commander/src/commands/core/upgrade.ts

Install and manage an instance of Klayr Core.

[IMPORTANT]
====
The commands for Klayr Core are not compatible with other distributions or with installations from the xref:{url_core_setup_binary}[binary script^].
To manage Klayr Core with Klayr Commander, first uninstall the old version and perform a fresh <<install,installation>>.
====

[[install]]
== klayr core:install NAME

Install an instance of Klayr Core.

[source,bash]
----
Install an instance of Klayr Core.

USAGE
  $ klayr core:install NAME

ARGUMENTS
  NAME  Klayr Core installation directory name.

OPTIONS
  -n, --network=mainnet|testnet|betanet|alphanet|devnet  [default: mainnet] Klayr Core network name.
  -r, --release-url=release-url                          Klayr Core download URL.

  -s, --snapshot-url=snapshot-url                        [default:
                                                         https://downloads.klayr.io/klayr/mainnet/blockch
                                                         ain.db.gz] Klayr Core blockchain snapshot URL.

  --klayr-version=klayr-version                            Klayr Core version.

  --no-snapshot                                          Install Klayr Core without a blockchain
                                                         snapshot.

  --no-start                                             Install Klayr Core without starting.

EXAMPLES
  core:install klayr-mainnet
  core:install --no-start klayr-mainnet
  core:install --no-snapshot klayr-mainnet
  core:install --klayr-version=2.0.0 klayr-mainnet
  core:install --network=testnet
  --release-url=https://downloads.klayr.io/klayr/mainnet/1.6.0/klayr-1.6.0-Linux-x86_64.tar.gz klayr-mainnet
  core:install --network=mainnet --snapshot-url=https://downloads.klayr.io/klayr/mainnet/blockchain.db.gz custom-mainnet
----

_See code: {url_github_commander_core_install}[dist/commands/core/install.ts^]_

== klayr core:logs NAME

Stream logs of a Klayr Core instance.

[source,bash]
----
USAGE
  $ klayr core:logs NAME

ARGUMENTS
  NAME  Klayr Core installation directory name.

EXAMPLE
  core:logs mainnet-latest
----

_See code: {url_github_commander_core_logs}[dist/commands/core/logs.ts^]_

== klayr core:restart NAME

Restart Klayr Core instance.

[source,bash]
----
USAGE
  $ klayr core:restart NAME

ARGUMENTS
  NAME  Klayr Core installation directory name.

EXAMPLE
  core:restart mainnet-latest
----

_See code: {url_github_commander_core_restart}[dist/commands/core/restart.ts^]_

== klayr core:start NAME

Start Klayr Core instance.

[source,bash]
----
USAGE
  $ klayr core:start NAME

ARGUMENTS
  NAME  Klayr Core installation directory name.

EXAMPLE
  core:start mainnet-latest

COMMANDS
  core:start:cache     Start the cache server.
  core:start:database  Start the database server.

----

_See code: {url_github_commander_core_start}[dist/commands/core/start/index.ts^]_

== klayr core:start:cache NAME

Start the cache server.

[source,bash]
----
USAGE
  $ klayr core:start:cache NAME

ARGUMENTS
  NAME  Klayr Core installation directory name.

EXAMPLE
  core:start:cache mainnet-latest
----

_See code: {url_github_commander_core_cache}[dist/commands/core/start/cache.ts^]_

== klayr core:start:database NAME

Start the database server.

[source,bash]
----
USAGE
  $ klayr core:start:database NAME

ARGUMENTS
  NAME  Klayr Core installation directory name.

EXAMPLE
  core:start:database mainnet-latest
----

_See code: {url_github_commander_core_database}[dist/commands/core/start/database.ts^]_

== klayr core:status NAME

Show the status of a Klayr Core instances.

[source,bash]
----
USAGE
  $ klayr core:status [NAME]

ARGUMENTS
  NAME  Klayr Core installation directory name.

EXAMPLES
  core:status
  core:status mainnet-latest
----

_See code: {url_github_commander_core_status}[dist/commands/core/status.ts^]_

== klayr core:stop NAME

Stop Klayr Core instance.

[source,bash]
----
USAGE
  $ klayr core:stop NAME

ARGUMENTS
  NAME  Klayr Core installation directory name.

EXAMPLE
  core:stop mainnet-latest

COMMANDS
  core:stop:cache     Stop the cache server.
  core:stop:database  Stop the database server.
----

_See code: {url_github_commander_core_stop}[dist/commands/core/stop/index.ts^]_

== klayr core:stop:cache NAME

Stop the cache server.

[source,bash]
----
USAGE
  $ klayr core:stop:cache NAME

ARGUMENTS
  NAME  Klayr Core installation directory name.

EXAMPLE
  core:stop:cache mainnet-latest
----

_See code: {url_github_commander_core_stop_cache}[dist/commands/core/stop/cache.ts^]_

== klayr core:stop:database NAME

Stop the database server.

[source,bash]
----
USAGE
  $ klayr core:stop:database NAME

ARGUMENTS
  NAME  Klayr Core installation directory name.

EXAMPLE
  core:stop:database mainnet-latest
----

_See code: {url_github_commander_core_stop_database}[dist/commands/core/stop/database.ts^]_

== klayr core:uninstall NAME

Uninstall an instance of Klayr Core.

[source,bash]
----
USAGE
  $ klayr core:uninstall NAME

ARGUMENTS
  NAME  Klayr Core installation directory name.

EXAMPLE
  core:uninstall mainnet-latest
----

_See code: {url_github_commander_core_uninstall}[dist/commands/core/uninstall.ts^]_

== klayr core:upgrade NAME

Upgrade an instance of Klayr Core, (Binary) to a specified or latest version.

NOTE: The `core:upgrade` command is only supported for Klayr Core versions > `2.0.0`.

[source,bash]
----
USAGE
  $ klayr core:upgrade NAME

ARGUMENTS
  NAME  Klayr Core installation directory name.

OPTIONS
  -r, --release-url=release-url  Klayr Core download URL.
  --klayr-version=klayr-version    Klayr Core version.

EXAMPLES
  core:upgrade klayr-mainnet
  core:upgrade --klayr-version=2.0.0 klayr-mainnet
  core:upgrade --release-url=https://downloads.klayr.io/klayr/mainnet/2.1.0/klayr-2.1.0-Linux-x86_64.tar.gz klayr-mainnet
----

_See code: {url_github_commander_core_upgrade}[dist/commands/core/upgrade.ts^]_
