= Configuration
Mona Bärenfänger <mona@lightcurve.io>
:description: How to configure Klayr Core, including using custom config files and enabling plugins from the command line.
// Settings
:toc:
:source-highlighter: coderay
:v_sdk: master
// External URLs
// Project URLs
:url_config: reference/cli.adoc
:url_config_clo: reference/cli.adoc#clo
:url_config_start: reference/cli.adoc#start
:url_config_structure: reference/cli.adoc#structure
:url_docker: management/docker.adoc
:url_enable_pom: management/enabling-misbehavior-report.adoc
:url_management_forging: management/forging.adoc
:url_pm2_restart: management/pm2.adoc#refreshing-restarting-klayr-core
:url_source: management/source.adoc
:url_sdk_plugins: v5@klayr-sdk::plugins/index.adoc

NOTE: A complete command reference with all available options for starting Klayr Core can be found in the xref:{url_config_start}[Klayr Core CLI].

== Using a network-specific default configuration

To quickly connect your Klayr Core node to a specific network, specify the desired network with the `--network` or `-n` flag.

This will use the default config file for the specific network when starting Klayr Core.
The default configurations are located in the `config` folder of Klayr Core.

[source,bash]
----
$ klayr-core start --network=NETWORK <1>
----

<1> `NETWORK` may be `mainnet`, `testnet` or `devnet`.

== Using a custom config file

Klayr Core uses the default config for connecting to the Mainnet by default.

However, it is possible to use Klayr Core with a custom config, by specifying the path to the config file with the `--config` or `-c` flag.

The custom config file needs to follow the JSON config structure of Klayr Core.
A straightforward and easy method is to copy one of the network-specific default configs of Klayr Core and adjust it to your requirements.

./home/klayr/
[source,bash]
----
cp .klayr/klayr-core/config/testnet/config.json custom-config.json
vim custom-config.json
----

NOTE: If you intend to connect the node to the Mainnet, change `testnet` to `mainnet` in the snippet above.

[source,bash]
----
$ klayr-core start --config=/home/klayr/custom-config.json --overwrite-config
----

NOTE: Remember to xref:{url_pm2_restart}[restart] the node for the new config changes to take effect.

== Enabling plugins

Plugins, including the HTTP API plugin are not enabled by default.
Use the dedicated flags to enable them on application start:

[source,bash]
----
$ klayr-core start --enable-forger-plugin --enable-http-api-plugin
----

Alternatively, enable the plugins directly in the config file, see <<using-a-custom-config-file>>.

[TIP]
====
For more detailed descriptions of the available plugins, go to the xref:{url_sdk_plugins}[].

See also xref:{url_enable_pom}[] and xref:{url_config_start}[Klayr Core CLI: start]
====
////
[IMPORTANT]
====
If you are using the Docker image, Klayr Core is configured in a slightly different manner.
Please go to the xref:{url_docker}[Docker image commands] page to find out more regarding the docker-specific configuration of the Klayr Core.
====

[[network_specific_config]]
== Network-specific config files

The root folder for all configurations is `config/`.
The *default* network is `devnet`.
To connect to another network, specify the `network` when starting the Klayr Core as described in xref:{url_config}[Config reference].
The *network specific configurations* can be found under `config/<network>/config.json`, whereby `<network>` can be any of these values listed below:

* `devnet`
* `betanet`

[IMPORTANT]
====
Do not override any value in the files mentioned above, as the changes will be overwritten everytime the Klayr Core is upgraded.
If a custom configuration is required, use the environment variables or alternatively create your own `.json` file and pass it as xref:{url_config_clo}[command line option].
====


== Custom config file

Only the values required to be overwritten are necessary.
For all other options the pre-defined values will be used as described in the <<order, Config Load Order>> section.

[NOTE]
====
The *Application* and *Commander application* both provide a `config.json`, which can be customized as desired.

For the *Source code*, the config file needs to be created separately and needs to be passed as described below:
====

[tabs]
=====
Application::
+
--
The Klayr Core application provides a custom `config.json` which is stored in the root folder of your Klayr Core installation by default.

For example, if Klayr Core is installed under `~/klayr-beta`, then the config is stored directly in `~/klayr-beta/config.json`.

The updated `config.json` will be used automatically when reloading the node with the following command:

[source,bash]
----
bash klayr.sh reload
----
--
Commander application::
+
--
Klayr Commander provides a custom `config.json` which is stored in the root folder of your Klayr Core instance by default.

For example, if Klayr Core is installed under `~/.klayr/instances/klayr-betanet`, then the config is stored directly in `~/.klayr/instances/klayr-beta/config.json`.

The `config.json` will be used automatically when reloading the node with the following command:

[source,bash]
----
klayr core:restart klayr-betanet
----
--
Source code::
+
--
[source,bash]
----
pm2 stop klayr <1>
KLAYR_CONFIG_FILE=<CONFIG_PATH> pm2 start klayr <2>
----
<1> Stop Klayr Core in the case whereby it is running.
<2> Replace `<CONFIG_PATH>` with the path to your custom config file.
--
=====
////
