= Docker commands
Mona Bärenfänger <mona@lightcurve.io>
:description: Describes how to manage Klayr Service with Docker.
:toc:
:idseparator: -
:idprefix:
:experimental:
:imagesdir: ../assets/images

:url_config: configuration/docker.adoc

== Start

.Inside of the `klayr-service` root folder
[source,bash]
----
make up
----

This will start Klayr Service with the default configuration, which in turn will connect to a Klayr Core Mainnet node.

In case a different node or network shall be used, xref:{url_config}[configure] Klayr Service accordingly.

== Stop

.Inside of the `klayr-service` root folder
[source,bash]
----
make down
----

This will stop Klayr Service.

== Show status of Docker containers

[source,bash]
----
docker ps
----

== Reset Klayr Service database

To reset the database of Klayr Service, drop the respective MYSQL and Redis databases.

Before resetting the database, stop Klayr Service:

 make down

Now connect to the Docker container in which you wish to reset the database. If you are not sure what to choose here, check the available containers via <<show-status-of-docker-containers>>.

[source,bash]
----
$ docker exec -it klayr-service_mysql_core_1 bash # <1>
----

<1> Connect to the interactive shell of the MYSQL Docker container in which you wish to reset the MYSQL database.

=== Drop MYSQL DB

[source,bash]
----
root@f1413b535254:/# mysql -u klayr -ppassword # <1>
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 2044
Server version: 8.0.27 MySQL Community Server - GPL

Copyright (c) 2000, 2021, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
mysql> drop database klayr; # <2>
mysql> create database klayr; # <3>
mysql> quit; # <4>
----


<1> Login to MYSQL with the `klayr` user.
<2> Drop the `klayr` database.
<3> Create a fresh database `klayr`.
<4> Log out from MYSQL by typing `quit;`. Log out of the docker container by pressing kbd:[CRTL] + kbd:[D].

=== Flush Redis DB

Reset the databases for Redis after dropping the MYSQL database:

[source,bash]
----
sudo docker exec -it klayr-service_redis_core_persistent_1 /bin/sh
redis-cli flushall
----

TIP: Log out of the docker container again by pressing kbd:[CRTL] + kbd:[D].

[NOTE]
====
The `flushall` command removes all existing Redis databases:

> Deletes all the keys of all the existing databases, not just the current selected one. This command never fails.

For more information check the Redis documentation: https://redis.io/commands/FLUSHALL[FLUSHALL]

To flush only a particular DB in Redis, execute the following command instead:
----
 redis-cli -n <db_number> flushdb
----
====

=== Start Klayr Service

After the databases are reset, start Klayr Service again as usual:

 make up

NOTE: When Klayr Service is started again after a database reset, then the process to reindex all the data is initiated. This can be quite time-consuming and may take up to 2 hours.

== Logging

To check the logs for the different microservices of Klayr Service, use the command `docker container logs CONTAINER`, where `CONTAINER` is the respective Docker container that holds the logs you wish to view.

For example, to see the logs for the Gateway microservice, execute:

[source,bash]
----
docker container logs klayr-service_gateway_1
----
