= How to enable the "Report Misbehavior" plugin
Mona Bärenfänger <mona@lightcurve.io>
// Settings
:toc:
:sectnums:
// External URLs
// Project URLs
:url_plugin_report_misbehavior: v5@klayr-sdk::plugins/report-misbehavior-plugin.adoc

The xref:{url_plugin_report_misbehavior}["Report Misbehavior" plugin] provides automatic detection of delegate misbehavior and sends a `reportDelegateMisbehavior` transaction to the running node.

To enable the plugin on your node, perform the following actions:

== Choose sender account

The plugin will use a specified sender account to sign the `reportDelegateMisbehavior` transactions.
To automatically sign the transaction, the encrypted passphrase of the account must be added to the plugin configuration.

NOTE: Please note that the respective account should have a high enough account balance to be able to send a misbehavior report transaction.

Encrypt the passphrase of the sender account before adding it to the configuration:

[source,bash]
----
$ klayr-core passphrase:encrypt
? Please enter passphrase:  [hidden]
? Please re-enter passphrase:  [hidden]
? Please enter password:  [hidden]
? Please re-enter password:  [hidden]
{"encryptedPassphrase":"iterations=1000000&cipherText=643bfbf1b6f1dc0ce740dd9fc9f27a682e476dc5de4e6c023deded4d3efe2822346226541106b42638db5ba46e0ae0a338cb78fb40bce67fdec7abbca68e20624fa6b0d7&iv=8a9c461744b9e70a8ba65edd&salt=3fe00b03d10b7002841857c1f028196e&tag=c57a798ef65f5a7be617d8737828fd58&version=1"}
----

== Plugin configuration

Add the encrypted passphrase to the configuration under `plugins.reportMisbehavior.encryptedPassphrase` in the node configuration:

.custom-config.json
[source,json]
----
"plugins": {
    "reportMisbehavior": {
        "encryptedPassphrase": "iterations=1000000&cipherText=643bfbf1b6f1dc0ce740dd9fc9f27a682e476dc5de4e6c023deded4d3efe2822346226541106b42638db5ba46e0ae0a338cb78fb40bce67fdec7abbca68e20624fa6b0d7&iv=8a9c461744b9e70a8ba65edd&salt=3fe00b03d10b7002841857c1f028196e&tag=c57a798ef65f5a7be617d8737828fd58&version=1",
    },
}
----

TIP: See more available configuration options at the xref:{url_plugin_report_misbehavior}[] reference.

== PM2 configuration

Add the environment variable `KLAYR_ENABLE_REPORT_MISBEHAVIOR_PLUGIN` to the pm2 config for Klayr Core:

.pm2.conf.json
[source,json]
----
{
  "name": "klayr-core",
  "script": "klayr-core start --overwrite-config",
  "env": {
    "KLAYR_NETWORK": "testnet",
    "KLAYR_CONFIG_FILE": "/home/klayr/klayr-core/custom-config.json",
    "KLAYR_ENABLE_REPORT_MISBEHAVIOR_PLUGIN": true
  }
}
----

== Restart the node

[source,bash]
----
pm2 start pm2.conf.json
----

== Authorization

The "Report Misbehavior" plugin provides a dedicated action to enable and disable the plugin on the node.

For example use the `klayr-client` package and write a small script which invokes the `reportMisbehavior:authorize` action on the node.

Install the `klayr-client` package:

[source,bash]
----
npm i @klayr/client
----

Write a small script to enable the plugin on the node:

.authorize-plugin.js
[source,js]
----
const { apiClient } = require('@klayr/client');
let clientCache;

const getClient = async () => {
  if (!clientCache) {
    clientCache = await apiClient.createWSClient('ws://localhost:8080/ws');
  }
  return clientCache;
};

getClient().then((client) => {
	client.invoke("reportMisbehavior:authorize", {
		password: "myPassword",
        enable: true
    }).then(res => {
		console.log(res);
		process.exit(0);
	});
});
----

Execute the script:

[source,bash]
----
$ node authorize-plugin.js
{ result: 'Successfully enabled the reporting of misbehavior.' }
----

That's it! The "Report Misbehavior" plugin is now successfully enabled on the node.
