= Testnet and Mainnet v3 migration guide
:toc: preamble
:experimental:
:idprefix:
:idseparator: -
:klayr-migrator: klayr-migrator-v1.0.2-linux-x64.tar.gz
// External URLs
:url_klayr_migrator: https://downloads.klayr.com/klayr-migrator/{klayr-migrator}
:url_wallet: https://klayr.com/wallet
:url_klayr_blog_migration: https://klayr.com/blog/development/announcing-klayr-testnet-v3-migration
:url_klayr_blog_migration_mainnet: https://klayr.com/blog/development/announcing-klayr-mainnet-v3-migration
// Project URLs
:url_core_install: setup/binary.adoc
:url_sdk_protocol_voteweight: klayr-v3@ROOT::understand-blockchain/klayr-protocol/consensus-algorithm.adoc#voting_and_weight

This guide explains how to migrate a Klayr Core v2.1.7 node to Klayr Core v3.x using the Klayr migrator.

The Klayr migrator CLI will generate a new genesis block for Klayr Core v3.
The new genesis block is created based on a snapshot of the old blockchain (running on Klayr Core v2.1.7) at a given height.
The Klayr migrator will not install Klayr Core v3, nor will it uninstall Klayr Core v2.1.7, these are steps that need to be done manually as described below.

[IMPORTANT]

====
All actively forging delegates on the Klayr Mainnet and the Klayr Testnet need to follow this guide to correctly migrate their nodes to the new network, in order to not miss any blocks after the network hard fork.

Optionally, anyone running a Klayr Core v2.1.7 who is not an actively forging delegate can participate in the migration process.
In this case, the following steps 1.4, 2.7, 2.8, and 2.9 in this guide can be skipped, as they are only relevant for delegates.
====

:sectnums:
:sectnumlevels: 5
== Preparation

.System requirements
[NOTE]

====
The following system requirements are recommended for running the migration script:

Memory::
* Machines with a minimum of 4 GB RAM for the Mainnet.
* Machines with a minimum of 2 GB RAM for the Testnet.

OS::
* Ubuntu 20.04
* Ubuntu 18.04

If you have Node.js installed ensure to use version 18.
====

=== Preparing Klayr Core v2.1.7

==== Ensure you are running the binary distribution of Klayr Core
If you are using a different distribution of Klayr Core v2.1.7, such as Docker, Commander or Source, it will be necessary to install the application/binary distribution.

==== Ensure you are running version 2.1.7 of Klayr Core
Ensure you are running version 2.1.7 of Klayr Core to be able to seamlessly migrate to Klayr Core 3.0.0.

Open `package.json` to check the `version` of your Klayr Core node.
If your version is lower than 2.1.7, ensure to update Klayr Core before proceeding with the migration.

=== Setting up the Klayr migrator

==== Download the migration script
Download the migration script by running the following command in the terminal:

[subs=attributes+]
[source,bash]
----
curl -o {klayr-migrator} {url_klayr_migrator}
----

==== Download checksum and verify
Download the checksum and verify the successful download of klayr-migrator.

{counter:seq3:A}) Download the checksum.

[subs=attributes+]
[source,bash]
----
curl -o {klayr-migrator}.SHA256 {url_klayr_migrator}.SHA256
----

{counter:seq3}) Run the following command in the terminal and ensure the output is `sha256sum: <file name>: OK`

[subs=attributes+]
[source,bash]
----
sha256sum -c {klayr-migrator}.SHA256
----

==== Extract and add to PATH

Unpack it, and then add it to the system path, in order to use it in the terminal:

[subs=attributes+]
[source,bash]
----
tar -xf ./{klayr-migrator}
----

Make the `klayr-migrator` command available in the PATH, e.g. by executing the following command:

[source,bash]
----
export PATH="$PATH:$HOME/klayr-migrator/bin" <1>
----

<1> Replace `$HOME` with the absolute path of where the `klayr-migrator` folder is located, in case it was extracted somewhere else other than in your home directory.

=== Setting up Klayr Core v3

Follow the guide how to xref:{url_core_install}[setup Klayr Core v3] for the binary distribution.

IMPORTANT: Don't start Klayr Core v3 yet.

=== Create a custom config with your delegate information

First copy the existing config file for the respective network.

[tabs]
====
Mainnet::
+
--
[source,bash]
----
cp ~/klayr-core/config/mainnet/config.json ~/klayr-core/config/mainnet/custom-config.json <1>
----
--
Testnet::
+
--
[source,bash]
----
cp ~/klayr-core/config/testnet/config.json ~/klayr-core/config/testnet/custom-config.json <1>
----
--
====

Next, use the CLI of Klayr Core v3 to generate the delegate configuration data.

[source,bash]
----
klayr-core forging:config --output custom-forging.json
----

After running the command, you will be prompted for your delegate passphrase and for the password that will be used to encrypt the passphrase, so it can be stored securely in the delegate configuration data.

----
? Please enter passphrase:  [hidden]
? Please re-enter passphrase:  [hidden]
? Please enter password:  [hidden]
? Please re-enter password:  [hidden]
----

After providing the required inputs, the delegate configuration data will be saved in the file `custom-forging.json`.

.Example of custom-forging.json
[source,js]
----
{
  forging: {
    delegates: [ <1>
        {
            address: "86555265f0110b4ed5a8cb95dbc732e77732c474",
            encryptedPassphrase: "iterations=1&salt=476d4299531718af8c88156aab0bb7d6&cipherText=663dde611776d87029ec188dc616d96d813ecabcef62ed0ad05ffe30528f5462c8d499db943ba2ded55c3b7c506815d8db1c2d4c35121e1d27e740dc41f6c405ce8ab8e3120b23f546d8b35823a30639&iv=1a83940b72adc57ec060a648&tag=b5b1e6c6e225c428a4473735bc8f1fc9&version=1",
            hashOnion: {
                "count": 1000000,
                "distance": 1000,
                "hashes": [
                    "ff2156e33c4aefa4a5a790edbe329f4a",
                    "5f86db180d4e63be6412d42d444dfb49",
                    "10fc37bb42d7f77030138e45795fef65",
                    "f04a306a73c5d7d94cc4f262b4d5ebb4",
                    //[...]
                    "ca41d52225f4b76140fc7f277731d326",
                    "fde61109609b74ba16d5ebd72a8b446f",
                    "9752dc2228492466d7c2046354d5fdfd"
                ]
            }
        }
    ]
  }
}
----

<1>  The list of delegates who are allowed to forge on this node.

Merge the forging config with the created custom config as shown in <<create-a-custom-config-with-your-delegate-information,step 1.4>> above, to add the delegate information to the application configuration:

[tabs]
====
Mainnet::
+
--
[source,bash]
----
TEMP_FILE=$( mktemp )
jq --slurp '.[0] * .[1]' ~/klayr-core/config/mainnet/custom-config.json ./custom-forging.json >$TEMP_FILE
mv $TEMP_FILE ~/klayr-core/config/mainnet/custom-config.json
----
--
Testnet::
+
--
[source,bash]
----
TEMP_FILE=$( mktemp )
jq --slurp '.[0] * .[1]' ~/klayr-core/config/testnet/custom-config.json ./custom-forging.json >$TEMP_FILE
mv $TEMP_FILE ~/klayr-core/config/testnet/custom-config.json
----
--
====

== Migration steps

=== Check the announced snapshot height

* For Mainnet: `16270292` +
For more information check the {url_klayr_blog_migration_mainnet}[Mainnet migration announcement^].
* For Testnet: `14075259` +
For more information check the {url_klayr_blog_migration}[Testnet migration announcement^].

The height is needed by `klayr-migrator` in the next step.
A snapshot of the blockchain will be created at this particular height, which will then be used to create the genesis block for the new blockchain.

=== Ensure Klayr Core v2.1.7 is fully synced with the network
Check the current block height of your node directly in the terminal by running the following command:

[tabs]
====
Mainnet::
+
--
./home/klayr/klayr-main
[source,bash]
----
$ bash klayr.sh status
Klayr configured for mainnet
[+] Klayr is running as PID: 24468
Current Block Height:   14992772
----
--
Testnet::
+
--
./home/klayr/klayr-test
[source,bash]
----
$ bash klayr.sh status
Klayr configured for testnet
[+] Klayr is running as PID: 24751
Current Block Height:  13279765
----
--
====

Compare the current height of your node to the network height in {url_wallet}[Klayr Desktop^], which is shown on the kbd:[Network] or kbd:[Blocks] pages.

If both heights are equal, it is verified that your node is fully synched with the network.

NOTE: To view the current height of the Klayr Testnet, use the network switcher of Klayr Desktop, which can be enabled in the settings.

=== Run klayr migrator

[IMPORTANT]
====
.When to start the migrator script?
`klayr-migrator` can be started any time before the announced snapshot height.
====

If you have added `klayr-migrator` to the PATH as described in the section <<setting-up-the-klayr-migrator>>, you can start the migration script by running the following command footnote:snap_footnote[Snap versions of Klayr Core store everything in `~/snap/klayr-core/current/.klayr/klayr-core` instead of `~/.klayr/klayr-core`] in the terminal:

[tabs]
====
Mainnet::
+
--
[source,bash]
----
klayr-migrator --snapshot-height ${snapshotHeight} --output ~/.klayr/klayr-core/config/mainnet/genesis_block.json --klayr-core-path ~/klayr-main
----
--
Testnet::
+
--
[source,bash]
----
klayr-migrator --snapshot-height ${snapshotHeight} --output ~/.klayr/klayr-core/config/testnet/genesis_block.json --klayr-core-path ~/klayr-test
----
--
====

* `--snapshot-height`:
The height on which the blockchain snapshot will be performed.
The snapshot height will be announced separately.
* `--output`:
The absolute path to the directory, where the newly generated genesis block should be saved.
* `--klayr-core-path`:
The absolute path to the directory, where the Klayr Core v2.1.7 node is located.

[TIP]

====
It is possible to use tools such as `screen` to run the Klayr migrator in the background.

With `screen` you can detach the current terminal window into the background:

.Example (Mainnet) footnote:snap_footnote[]
[source,bash]
----
screen -dmSL migration klayr-migrator --snapshot-height ${snapshotHeight} --output ~/.klayr/klayr-core/config/mainnet/genesis_block.json --klayr-core-path ~/klayr-main
----

Shortly before the migration occurs, it is possible to reattach to it in order to check if everything is working correctly.

First check the name of the detached screen:

[source,bash]
----
screen -ls
----

This returns a list of all detached screens with `screen`:

----
There is a screen on:
	1842.migration	(05/07/2021 12:35:59 PM)	(Detached)
1 Socket in /run/screen/S-klayr.
----

Use `screen -r` and the name of the detached screen you want to connect to

[source,bash]
----
screen -r 1842.migration
----
====

=== Wait until the network reaches the snapshot height

Observe if `klayr-migrator` finishes successfully, (this takes about 30-60 minutes from the snapshot height).

After the snapshot height is reached, delegates have approximately 2 hours time to start their Klayr Core v3 and enable forging, to ensure they will not miss any blocks after the hardfork.

If the node is started at a later point in time, it will simply sync to the current network height.
For delegates, this might result in them missing a block, for everyone else it will not have any impact.

=== Stop Klayr Core v2.1.7

After the `klayr-migrator` script has finished and the announced snapshot height has passed, there is no reason to continue running Klayr Core v2.1.7 and therefore it is recommended to stop it.

First ensure, that Klayr Core will not start again by removing the existing cronjob:

[source,bash]
----
crontab -e
----

Choose your favorite editor to open the `crontab` file and remove the following line:

 @reboot /bin/bash /home/klayr/klayr-test/klayr.sh start > /home/klayr/klayr-test/cron.log 2>&1

Save and close the `crontab` file again.

Navigate into the root folder of your Klayr Core v2.1.7 installation and run the following command to stop the old Klayr Core version:

[source,bash]
----
bash klayr.sh stop
----

Last but not least, remove the folder with Klayr Core v2.1.7, e.g. by executing the following:

[tabs]
====
Mainnet::
+
--
[source,bash]
----
rm -r klayr-main
----
--
Testnet::
+
--
[source,bash]
----
rm -r klayr-test
----
--
====

=== Start Klayr Core v3
Use the Klayr Core CLI to start Klayr Core v3.

Run the following command in the terminal and check the logs in the console to verify that Klayr Core starts successfully:

[tabs]
====
Mainnet::
+
--
[source,bash]
----
klayr-core start --network mainnet --api-ipc --config=/home/klayr/klayr-core/config/mainnet/custom-config.json
----
--
Testnet::
+
--
[source,bash]
----
klayr-core start --network testnet --api-ipc --config=/home/klayr/klayr-core/config/testnet/custom-config.json
----
--
====

Press kbd:[CTRL] + kbd:[C] to stop the process again.

Install PM2 to run Klayr Core in the background:

[source,bash]
----
npm i -g pm2
----

Create a pm2 config as shown in the example below:

[tabs]
====
Mainnet::
+
--
.~/klayr-core/pm2.conf.json
[source,json]
----
{
  "name": "klayr-core",
  "script": "klayr-core start --api-ipc",
  "env": {
    "KLAYR_NETWORK": "mainnet",
    "KLAYR_CONFIG_FILE": "/home/klayr/klayr-core/config/mainnet/custom-config.json"
  }
}
----
--
Testnet::
+
--
.~/klayr-core/pm2.conf.json
[source,json]
----
{
  "name": "klayr-core",
  "script": "klayr-core start --api-ipc",
  "env": {
    "KLAYR_NETWORK": "testnet",
    "KLAYR_CONFIG_FILE": "/home/klayr/klayr-core/config/testnet/custom-config.json"
  }
}
----
--
====

TIP: All available options for `scripts` and `env` can be found in `klayr-core start --help`.

After creating the config, start it with the following command:

./home/klayr/klayr-core/
[source,bash]
----
pm2 start pm2.conf.json
----

This will start Klayr Core in the background.

You can verify that the node is running correctly by executing the following command:

[source,bash]
----
klayr-core node:info
----

This will return certain general node information, for example as shown below:
----
{"version":"3.0.0.5e1a7cf","networkVersion":"2.0","networkIdentifier":"01e47ba4e3e57981642150f4b45f64c2160c10bac9434339888210a4fa5df097","lastBlockID":"a98f7027ee16c8f8169ba676a72679dd8e6f56d83e93fec813b8f3041fb9c03d","height":670287,"finalizedHeight":670148,"syncing":false,"unconfirmedTransactions":0,"genesisConfig":{"blockTime":10,"communityIdentifier":"Klayr","maxPayloadLength":15360,"bftThreshold":68,"minFeePerByte":1000,"baseFees":[{"moduleID":5,"assetID":0,"baseFee":"1000000000"}],"rewards":{"milestones":["500000000","400000000","300000000","200000000","100000000"],"offset":2160,"distance":3000000},"minRemainingBalance":"5000000","activeDelegates":101,"standbyDelegates":2,"delegateListRoundOffset":2},"registeredModules":[{"id":2,"name":"token","actions":[],"events":[],"reducers":["token:credit","token:debit","token:getBalance","token:getMinRemainingBalance"],"transactionAssets":[{"id":0,"name":"transfer"}]},{"id":3,"name":"sequence","actions":[],"events":[],"reducers":[],"transactionAssets":[]},{"id":4,"name":"keys","actions":[],"events":[],"reducers":[],"transactionAssets":[{"id":0,"name":"registerMultisignatureGroup"}]},{"id":5,"name":"dpos","actions":["dpos:getAllDelegates","dpos:getUnlockings"],"events":[],"reducers":[],"transactionAssets":[{"id":0,"name":"registerDelegate"},{"id":1,"name":"voteDelegate"},{"id":2,"name":"unlockToken"},{"id":3,"name":"reportDelegateMisbehavior"}]},{"id":1000,"name":"legacyAccount","actions":["legacyAccount:getUnregisteredAccount"],"events":[],"reducers":[],"transactionAssets":[{"id":0,"name":"reclaimKLY"}]}]}
----

TIP: Use the `--pretty` flag to return the response in formatted JSON: `klayr-core node:info --pretty`.

=== Check new account address

It is necessary to know your new address to enable forging for your delegate in the new network.

Use the following command to view your new account address.
You will be prompted for your passphrase from which the other account details will be generated.

[source,bash]
----
klayr-core account:show
----

After running the above command, you will be prompted for your delegate passphrase.

----
? Please enter passphrase:  [hidden]
? Please re-enter passphrase:  [hidden]
----

This will return an object including `privateKey`, `publicKey`, `address`, and `binaryAddress`.

The value under `binaryAddress` is used to self-vote for the delegate account and to enable forging in the next steps.

=== Self-voting

In the new DPoS rules, delegates need to self-vote with a significant amount of tokens to be able to reach forging positions.

For more information how self-voting affects the vote weight, see xref:{url_sdk_protocol_voteweight}[Delegates, voting, and delegate weight, (Klayr Protocol)].

==== Voting with Klayr Desktop

Use Klayr Desktop to cast the self-vote conveniently from a user interface.

Just login with your passphrase, after updating Klayr Desktop to the latest 2.x version.

See the two example videos below, which show how to vote with Klayr Desktop v2:

video::CKwf2u-QfuU[youtube]

video::KAPor0lMz5U[youtube]

==== Voting via Klayr Core CLI

Use the Klayr Core CLI to cast the self-vote with the desired amount of tokens from the command line.

[source,bash]
----
$ klayr-core transaction:create 5 1 100000000
? Please enter: votes(delegateAddress, amount):  89aa5fc8861d392f60662f76a379cc348fe97d28, 148000000000
? Want to enter another votes(delegateAddress, amount) No
? Please enter passphrase:  [hidden]
? Please re-enter passphrase:  [hidden]
{"transaction":"0805100118012080c2d72f2a2024350a05e078b181fa8f3c273ca9882a8f5ed6efbaf3d1537665f9480635273f321f0a1d0a1489aa5fc8861d392f60662f76a379cc348fe97d281080a0e6d7ce083a403aef0012b05f3d962e3bc4b1ba70d6cc4fea783e24c02c36bc644e283ef2dd7618ec072594505c7ab8ce2a1e22dda5e90c51be79d06ac4871daf8430ff6a330b"}
$ klayr-core transaction:send 0805100118012080c2d72f2a2024350a05e078b181fa8f3c273ca9882a8f5ed6efbaf3d1537665f9480635273f321f0a1d0a1489aa5fc8861d392f60662f76a379cc348fe97d281080a0e6d7ce083a403aef0012b05f3d962e3bc4b1ba70d6cc4fea783e24c02c36bc644e283ef2dd7618ec072594505c7ab8ce2a1e22dda5e90c51be79d06ac4871daf8430ff6a330b
Transaction with id: '6a6121adf6a73a857bef92eaec9c29545f53c9196a16faa1eafdf58012f5a2e5' received by node.
----

==== Voting with a multisignature account

All accounts which had a second passphrase registered in Klayr Core v2 are converted to multisignature accounts which need 2 mandatory signatures.
The voting process therefore works a little different for accounts with a second passphrase:

[source,bash]
----
$ klayr-core transaction:create 5 1 100000000
? Please enter: votes(delegateAddress, amount):  331e287263c8166febde9d77a5f333df75056c74, 5555000000000
? Want to enter another votes(delegateAddress, amount) No
? Please enter passphrase:  [hidden] # <1>
? Please re-enter passphrase:  [hidden]
{"transaction":"0805100118002080c2d72f2a2030c07dbb72b41e3fda9f29e1a4fc0fce893bb00788515a5e6f50b80312e2f48332200a1e0a14331e287263c8166febde9d77a5f333df75056c741080f8e9fcabc3023a4072b159f5a7d2934b1a5131b36f711e9ca8fcd2cce68c607eb468cb1926b84fa33205fd294df23cd02e5b2107849b651e5a9b8e064c59ca16eb1f72e90065330f"}
# Use the transaction hex output from above in the command below
$ klayr-core transaction:sign 0805100118002080c2d72f2a2030c07dbb72b41e3fda9f29e1a4fc0fce893bb00788515a5e6f50b80312e2f48332200a1e0a14331e287263c8166febde9d77a5f333df75056c741080f8e9fcabc3023a4072b159f5a7d2934b1a5131b36f711e9ca8fcd2cce68c607eb468cb1926b84fa33205fd294df23cd02e5b2107849b651e5a9b8e064c59ca16eb1f72e90065330f \
--mandatory-keys="30c07dbb72b41e3fda9f29e1a4fc0fce893bb00788515a5e6f50b80312e2f483" \ # <2>
--mandatory-keys="f7a16edaf7995d522d5e6ac69d7325df76f5883dd084409eb13df8d61c33abfb" \ # <3>
--sender-public-key="30c07dbb72b41e3fda9f29e1a4fc0fce893bb00788515a5e6f50b80312e2f483" # <4>
? Please enter passphrase:  [hidden] # <5>
? Please re-enter passphrase:  [hidden]
{"transaction":"0805100118002080c2d72f2a2030c07dbb72b41e3fda9f29e1a4fc0fce893bb00788515a5e6f50b80312e2f48332200a1e0a14331e287263c8166febde9d77a5f333df75056c741080f8e9fcabc3023a4072b159f5a7d2934b1a5131b36f711e9ca8fcd2cce68c607eb468cb1926b84fa33205fd294df23cd02e5b2107849b651e5a9b8e064c59ca16eb1f72e90065330f3a00"}
# Use the transaction hex output from above in the command below
$ klayr-core transaction:sign 0805100118002080c2d72f2a2030c07dbb72b41e3fda9f29e1a4fc0fce893bb00788515a5e6f50b80312e2f48332200a1e0a14331e287263c8166febde9d77a5f333df75056c741080f8e9fcabc3023a4072b159f5a7d2934b1a5131b36f711e9ca8fcd2cce68c607eb468cb1926b84fa33205fd294df23cd02e5b2107849b651e5a9b8e064c59ca16eb1f72e90065330f \
--mandatory-keys="30c07dbb72b41e3fda9f29e1a4fc0fce893bb00788515a5e6f50b80312e2f483" \
--mandatory-keys="f7a16edaf7995d522d5e6ac69d7325df76f5883dd084409eb13df8d61c33abfb" \
--sender-public-key="30c07dbb72b41e3fda9f29e1a4fc0fce893bb00788515a5e6f50b80312e2f483"
? Please enter passphrase:  [hidden] # <6>
? Please re-enter passphrase:  [hidden]
{"transaction":"0805100118002080c2d72f2a2030c07dbb72b41e3fda9f29e1a4fc0fce893bb00788515a5e6f50b80312e2f48332200a1e0a14331e287263c8166febde9d77a5f333df75056c741080f8e9fcabc3023a4072b159f5a7d2934b1a5131b36f711e9ca8fcd2cce68c607eb468cb1926b84fa33205fd294df23cd02e5b2107849b651e5a9b8e064c59ca16eb1f72e90065330f3a401c644e345238bc27f0f6af84ed8be2c8f3b70d30d91b3af45da511cb0da61f80061fbb05bab09e0606a3f9d715176d49cdf5400dd299bd2e04bd8573a6933d04"}
# Use the transaction hex output from above in the command below
$ klayr-core transaction:send 0805100118002080c2d72f2a2030c07dbb72b41e3fda9f29e1a4fc0fce893bb00788515a5e6f50b80312e2f48332200a1e0a14331e287263c8166febde9d77a5f333df75056c741080f8e9fcabc3023a4072b159f5a7d2934b1a5131b36f711e9ca8fcd2cce68c607eb468cb1926b84fa33205fd294df23cd02e5b2107849b651e5a9b8e064c59ca16eb1f72e90065330f3a401c644e345238bc27f0f6af84ed8be2c8f3b70d30d91b3af45da511cb0da61f80061fbb05bab09e0606a3f9d715176d49cdf5400dd299bd2e04bd8573a6933d04
Transaction with id: 'cf1e7af1b385a630c893ac45c9a4cdf5536769ba6e678a9779ff9af135ee5ec9' received by node.
----

<1> Use the *passphrase* of the *first* account.
<2> Use the *public key* of the *first* account.
<3> Use the *public key* of the *second* account.
<4> Use the *public key* of the *first* account.
<5> Use the *passphrase* of the *first* account.
<6> Use the *passphrase* of the *second* account.

=== Enable forging

The final step is to enable forging on the node for your delegate.

Again, this can be done by using the Klayr Core CLI.
Just use it with your own delegate address.

[source,bash]
----
klayr-core forging:enable 89aa5fc8861d392f60662f76a379cc348fe97d28 0 0 0 <1>
----

<1> Replace the address with your delegate address in hexadecimal representation.

The `0 0 0` stands for the three variables, `height`, `maxHeightPreviouslyForged`, and `maxHeightPrevoted`.
These three variables need to be set to `0` for every delegate who starts forging for the first time in the network, which will be the case for all delegates participating in the migration.

[TIP]

====
When a delegate has already forged in the network, it is necessary to check which values to use for `height`, `maxHeightPreviouslyForged`, and `maxHeightPrevoted`.

These values can be checked by running the following command:

[source,bash]
----
klayr-core forging:status
[{"address":"89aa5fc8861d392f60662f76a379cc348fe97d28","forging":true,"height":670237,"maxHeightPrevoted":670159,"maxHeightPreviouslyForged":670187}]
----
====
