= Client
Mona Bärenfänger <mona@lightcurve.io>
:description: Technical references for the client package of Klayr Elements, including all sub-packages and general usage instructions.
:page-aliases: klayr-elements/packages/client.adoc, reference/klayr-elements/packages/client.adoc
:toc:
:url_elements_api: references/klayr-elements/api-client.adoc
:url_elements_constants: references/klayr-elements/constants.adoc
:url_elements_cryptography: references/klayr-elements/cryptography.adoc
:url_elements_passphrase: references/klayr-elements/passphrase.adoc
:url_elements_transactions: references/klayr-elements/transactions.adoc
:url_elements_codec: references/klayr-elements/codec.adoc
:url_elements_utils: references/klayr-elements/utils.adoc
:url_elements_tree: references/klayr-elements/tree.adoc
:url_elements_validator: references/klayr-elements/validator.adoc

The @klayr/client package provides a default set of packages for use by clients of the Klayr network.

[NOTE]
====
The `Client` package is a collection of the following packages:

xref:{url_elements_api}[api-client], xref:{url_elements_codec}[codec],
xref:{url_elements_cryptography}[cryptography], xref:{url_elements_passphrase}[passphrase],
xref:{url_elements_transactions}[transactions], xref:{url_elements_utils}[utils],
xref:{url_elements_tree}[tree], xref:{url_elements_validator}[validator]
====

== Installation

To add Klayr client as a dependency of your project execute the following command:

[source,bash]
----
$ npm install @klayr/client
----

== Upgrade

To perform an upgrade, execute the following command:

[source,bash]
----
npm update @klayr/client
----

== Usage

Import using ES6 modules syntax:

[source,js]
----
import klayr from '@klayr/client';
----

Or using Node.js modules:

[source,js]
----
const klayr = require('@klayr/client');
----

Or import specific namespaced functionality:

[source,js]
----
import { apiClient, transactions } from '@klayr/client';
// or
const { apiClient, transactions } = require('@klayr/client');

----

=== Creating an APIClient

[source,js]
----
const { apiClient } = require('@klayr/client');

let clientCache;

export const getClient = async () => {
    if (!clientCache) {
        clientCache = await apiClient.createWSClient('ws://localhost:8080/ws');
    }
    return clientCache;
};

export const useClient = async () => {
    const client = await getClient();
    const blockAtHeight123 = await client.block.getByHeight(123);
    client.subscribe('pluginAlias:eventAlias', ({ data }) => {
      console.log(data.info);
    });
};
----
