= Transactions
Mona Bärenfänger <mona@lightcurve.io>
:description: Technical references regarding the transactions package consisting of usage examples, available options and example responses.
:page-aliases: klayr-elements/packages/transactions.adoc, reference/klayr-elements/packages/transactions.adoc
:toc:

Transaction utility functions are defined in `@klayrhq/klayr-transactions`.
The functionalities can be accessed through package `@klayrhq/klayr-transactions`, `@klayrhq/klayr-client` or `klayr-sdk`.

== Installation

[source,bash]
----
$ npm install @klayrhq/klayr-transactions
----

== Upgrade

To perform an upgrade, execute the following command:

[source,bash]
----
npm update @klayrhq/klayr-transactions
----

== Signing transactions

=== signTransaction

Signs a transaction with a given networkIdentifier and passphrase.
This returns a transaction object with a signature.

[source,js]
----
signTransaction(
  // schema defined in custom asset to be signed
  assetSchema: Schema,
  // transaction object in JavaScript object format
  transactionObject: Record<string, unknown>,
  networkIdentifier: Buffer,
  passphrase: string,
): Record<string, unknown>;
----

=== signMultiSignatureTransaction

Signs a transaction with a given passphrase as a multi signature account.
This method can be used for signing registerMultisignatureGroup by setting the includeSenderSignature to true.

[source,js]
----
signMultiSignatureTransaction(
  // schema defined in the custom asset to be signed
  assetSchema: Schema,
  // transaction object in JavaScript object format
  transactionObject: Record<string, unknown>,
  networkIdentifier: Buffer,
  passphrase: string,
  // keys which correspond to the sender account of the transaction
  keys: {
    mandatoryKeys: Buffer[],
    optionalKeys: Buffer[],
  },
  // By setting true, signature corresponds to the sender public key will also be included in the signatures
  // This should be used for registerMultisignatureGroup transaction
  includeSenderSignature = false,
): Record<string, unknown>
----

=== getBytes

Validates the transaction against the asset schema and returns transaction bytes.

[source,js]
----
getBytes (
  // schema defined in custom asset
  assetSchema: Schema,
  // transaction object in JavaScript object format
  transactionObject: Record<string, unknown>,
): Buffer;
----

=== getSigningBytes

Validates the transaction against the asset schema and returns transaction bytes for signing.

[source,js]
----
getSigningBytes (
  // schema defined in custom asset to be signed
  assetSchema: Schema,
  // transaction object in JavaScript object format
  transactionObject: Record<string, unknown>,
): Buffer;
----

== Changing between formats

=== convertBeddowsToKLY

This converts amounts in Beddows (the smallest denomination), to the amounts in one KLY.

==== Syntax

[source,js]
----
convertBeddowsToKLY(amount)
----

==== Parameters

`amount`: `string` decimal representation of amount to be converted.

==== Return value

`string`: Amount in KLY.

==== Examples

[source,js]
----
transactions.convertBeddowsToKLY('100000'); // '0.001'
----

=== convertKLYToBeddows

This converts the amounts in KLY to the amounts in Beddows, (the smallest denomination).

==== Syntax

[source,js]
----
convertKLYToBeddows(amount)
----

==== Parameters

`amount`: `string` decimal representation of amount to be converted.

==== Return value

`string`: Amount in Beddows.

==== Examples

[source,js]
----
transactions.convertKLYToBeddows('0.001'); // '100000'
----

== Validating transactions

=== validateTransaction

Statically validates the transaction object input using the schema.

[source,js]
----
validateTransaction(
  // schema defined in custom asset to be signed
  assetSchema: Schema,
  // transaction object in JavaScript object format
  transactionObject: Record<string, unknown>,
): KlayrValidationError | Error | undefined;
----

== Calculating the minimum fee for a transaction

=== computeMinFee

Returns the minimal fee for a transaction.

[source,js]
----
computeMinFee(
// schema defined in custom asset to be signed
  assetSchema: Schema,
  // transaction object in JavaScript object format
  transactionObject: Record<string, unknown>,
  options?: {
    minFeePerByte: number,
    baseFees: { moduleID: number, assetID: number, baseFee: number}[],
    numberOfSignatures: number,
  }
): bigint
----
