= Klayr Core with Klayr Commander Administration
Mona Bärenfänger <mona@lightcurve.io>
:description: The Klayr Core Commander Administration describes all relevant commands to manage Klayr Core through the Command-line with Klayr Commander.
:toc:

This section covers how to work with a Binary installation of Klayr Core.
Further information can be found by referring to the following commands reference list.

== Basic Commands

The available basic commands which can be used to manage your Klayr node are displayed here below:

=== Install

NOTE: For more information, please see the xref:setup/commander.adoc[Setup page of Klayr Core with Klayr Commander].

[tabs]
====
Mainnet::
+
--
[source,bash]
----
klayr core:install klayr-mainnet
----
--
Testnet::
+
--
[source,bash]
----
klayr core:install --network=testnet klayr-testnet
----
--
====

=== Uninstall

[tabs]
====
Mainnet::
+
--
[source,bash]
----
klayr core:uninstall klayr-mainnet
----
--
Testnet::
+
--
[source,bash]
----
klayr core:uninstall klayr-testnet
----
--
====

=== Status

Check the status of the Klayr Core Node.

[tabs]
====
Mainnet::
+
--
[source,bash]
----
klayr core:status klayr-mainnet
----
--
Testnet::
+
--
[source,bash]
----
klayr core:status klayr-testnet
----
--
====

=== Upgrade

NOTE: For more information, please see the xref:upgrade/commander.adoc[Upgrade page of Klayr Core with Klayr Commander].

[tabs]
====
Mainnet::
+
--
[source,bash]
----
klayr core:upgrade klayr-mainnet
----
--
Testnet::
+
--
[source,bash]
----
klayr core:upgrade klayr-testnet
----
--
====

=== Start

Start Klayr Core and PostgreSQL.

[tabs]
====
Mainnet::
+
--
[source,bash]
----
klayr core:start klayr-mainnet
----
--
Testnet::
+
--
[source,bash]
----
klayr core:start klayr-testnet
----
--
====

=== Stop

Stop Klayr Core and PostgreSQL.

[tabs]
====
Mainnet::
+
--
[source,bash]
----
klayr core:stop klayr-mainnet
----
--
Testnet::
+
--
[source,bash]
----
klayr core:stop klayr-testnet
----
--
====

=== Restart

Reload Klayr Core and pick up changes to config.json.

[tabs]
====
Mainnet::
+
--
[source,bash]
----
klayr core:restart klayr-mainnet
----
--
Testnet::
+
--
[source,bash]
----
klayr core:restart klayr-testnet
----
--
====

=== Logs

Monitor,(tail) the log file of Klayr.

[tabs]
====
Mainnet::
+
--
[source,bash]
----
klayr core:logs klayr-mainnet
----
--
Testnet::
+
--
[source,bash]
----
klayr core:logs klayr-testnet
----
--
====

=== Help

To access the Help menu please execute the following command listed below:

[source,bash]
----
klayr core
----

== Advanced Commands

The advanced commands which can be used to manage your Klayr node, can be seen in the commands reference list below:

=== Start database only

This command is used to start database instances apart from the Klayr process.

[tabs]
====
Mainnet::
+
--
[source,bash]
----
klayr core:start:database klayr-mainnet
----
--
Testnet::
+
--
[source,bash]
----
klayr core:start:database klayr-testnet
----
--
====

=== Stop database only

This command is used to stop all database instances apart from the Klayr process.

[tabs]
====
Mainnet::
+
--
[source,bash]
----
klayr core:stop:database klayr-mainnet
----
--
Testnet::
+
--
[source,bash]
----
klayr core:stop:database klayr-testnet
----
--
====

=== Start cache only

This command is used to start caching apart from the Klayr process.

[tabs]
====
Mainnet::
+
--
[source,bash]
----
klayr core:start:cache klayr-mainnet
----
--
Testnet::
+
--
[source,bash]
----
klayr core:start:cache klayr-testnet
----
--
====

=== Stop cache only

This command is used to stop all caching apart from the Klayr process.

[tabs]
====
Mainnet::
+
--
[source,bash]
----
klayr core:stop:cache klayr-mainnet
----
--
Testnet::
+
--
[source,bash]
----
klayr core:stop:cache klayr-testnet
----
--
====
