= References
Mona Bärenfänger <mona@lightcurve.io>
:description: This section provides an overview of the references available for the Klayr Elements packages and the Klayr Commander.
:toc:
:page-previous: /klayr-sdk/tutorials.html
:page-previous-title: Tutorials

:url_klayr_elements: reference/klayr-elements/index.adoc
:url_klayr_commander: reference/klayr-commander/commands.adoc
:url_klayr_packages: reference/klayr-elements/index.adoc
:url_klayr_api_client: reference/klayr-elements/api-client.adoc
:url_klayr_bft: reference/klayr-elements/bft.adoc
:url_klayr_chain: reference/klayr-elements/chain.adoc
:url_klayr_client: reference/klayr-elements/client.adoc
:url_klayr_constants: reference/klayr-elements/constants.adoc
:url_klayr_cryptography: reference/klayr-elements/cryptography.adoc
:url_klayr_dpos: reference/klayr-elements/dpos.adoc
:url_klayr_packages: reference/klayr-elements/index.adoc
:url_klayr_p2p: reference/klayr-elements/p2p.adoc
:url_klayr_passphrase: reference/klayr-elements/passphrase.adoc
:url_klayr_trans-pool: reference/klayr-elements/transaction-pool.adoc
:url_klayr_transactions: reference/klayr-elements/transactions.adoc
:url_klayr_validator: reference/klayr-elements/validator.adoc
:url_klayr_commander_commands: reference/klayr-commander/commands.adoc
:url_klayr_core: reference/klayr-commander/klayr-core.adoc
:url_sens_inputs: reference/klayr-commander/sensitive-inputs.adoc
:url_commander_overview: reference/klayr-commander/index.adoc
:url_user_guide: reference/klayr-commander/user-guide.adoc
:url_api_specification: reference/api.adoc
:url_changelog: reference/changelog.adoc
:url_config: reference/config.adoc
:url_framework: reference/klayr-framework/index.adoc


The references section is designed to provide the user with a comprehensive description of all the necessary specifications.
A brief overview of the applicable references are listed below, in order to assist the user in locating the relevant information required.

Firstly the  xref:{url_api_specification}[API specification] provides an in-depth definition of the API endpoints, followed by the  xref:{url_config}[SDK Configuration reference] which contains a detailed example explaining the default values. This is followed by the xref:{url_changelog}[Developer changelog] which encompasses an extensive description of the updated database and api changes that are relevant for developers when updating their application to the latest version of the Klayr SDK.

The xref:{url_commander_overview}[Klayr Commander] reference section comprises of the setup, installation and configuration. In addition the following  xref:{url_klayr_commander_commands}[Commands], xref:{url_klayr_core}[Core commands] and xref:{url_sens_inputs}[Sensitive inputs] are also covered separately, together with useful examples in order to assist the end-user.

Within the xref:{url_klayr_elements}[Klayr Elements] references the npm package lists, together with the relevant links and specifications can be found.
Furthermore, the following package links listed in the sub-sections below can be accessed, which provides all of the reference material required including the parameters, constants and a variety of workable examples:


    * xref:{url_klayr_api_client}[API client]
    * xref:{url_klayr_bft}[BFT]
    * xref:{url_klayr_chain}[Chain]
    * xref:{url_klayr_client}[Client]
    * xref:{url_klayr_constants}[Constants]
    * xref:{url_klayr_cryptography}[Cryptography]
    * xref:{url_klayr_dpos}[DPoS]
    * xref:{url_klayr_p2p}[Peer-to-Peer]
    * xref:{url_klayr_passphrase}[Passphrase]
    * xref:{url_klayr_trans-pool}[Transactions pool]
    * xref:{url_klayr_transactions}[Transactions]
    * xref:{url_klayr_validator}[Validator]

Finally, the  xref:{url_framework}[Klayr Framework] provides the end-user with the architectural overview, including the modules, channels, controller and components references.

These references have been constructed in a concise and explanatory manner, covering each specific topic to provide the user with the necessary reference information.

